// components/BackgroundGrid.vue
<script setup lang="ts">
defineProps<{
  bgColor?: string;
}>();

const svgElement = ref<HTMLElement | null>(null);
const width = computed(() => svgElement.value?.clientWidth || 768);
const height = computed(() => svgElement.value?.clientHeight || 768);
const size = computed(() => {
  const widthPercentage = window.innerWidth <= 768 ? 0.05 : 0.02;
  return Math.floor(width.value * widthPercentage);
});
</script>

<template>
  <svg
    ref="svgElement"
    data-nosnippet
    class="absolute left-0 top-0 z-0 w-full h-full"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <template v-for="x in Math.ceil(width / size)">
      <rect
        v-for="y in Math.floor(Math.random() * (height / 2 / size))"
        :key="`${x}-${y}`"
        :x="(x - 1) * size"
        :y="height - size * y"
        :width="size"
        :height="size"
        :style="{
          // animationDelay: `${Math.random() * 5}s`,
          // animationDuration: `${Math.random() * 5 + 2}s`,
          fill: bgColor || '#0c0c0c',
          stroke: bgColor || '#0c0c0c',
          opacity: Number(Math.random().toFixed(2)),
        }"
      />
      <!-- class="opacity-0 animate-pulse" -->
      <rect
        v-for="y in Math.floor(Math.random() * (height / 2 / size))"
        :key="`${x}-${y}`"
        :x="(x - 1) * size"
        :y="size * (y - 1)"
        :width="size"
        :height="size"
        :style="{
          // animationDelay: `${Math.random() * 5}s`,
          // animationDuration: `${Math.random() * 5 + 2}s`,
          fill: bgColor || '#0c0c0c',
          stroke: bgColor || '#0c0c0c',
          opacity: Number(Math.random().toFixed(2)),
        }"
      />
      <!-- class="opacity-0 animate-pulse" -->
    </template>
  </svg>
</template>

// apps/web/src/lib/components/BackgroundGrid.svelte
<script lang="ts">
	import { browser } from '$app/environment';
	import type { Snippet } from 'svelte';

	interface Props {
		bgColor?: string;
		children: Snippet;
	}

	let { bgColor = '#0c0c0c', children }: Props = $props();

	let svgElement: SVGSVGElement | null = $state(null);
	let width = $state(768);
	let height = $state(768);

	let size = $derived.by(() => {
		if (!browser) return 15;
		const widthPercentage = window.innerWidth <= 768 ? 0.05 : 0.02;
		return Math.floor(width * widthPercentage);
	});

	let columns = $derived(Math.ceil(width / size));

	function getRandomRects(maxCount: number): number[] {
		const count = Math.floor(Math.random() * maxCount);
		return Array.from({ length: count }, (_, i) => i + 1);
	}

	$effect(() => {
		if (svgElement) {
			width = svgElement.clientWidth || 768;
			height = svgElement.clientHeight || 768;
		}
	});
</script>

<div class="corner-brackets group relative bg-[#131313] p-5">
	<svg
		bind:this={svgElement}
		data-nosnippet
		class="absolute left-0 top-0 z-0 h-full w-full"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
	>
		{#each Array.from({ length: columns }, (_, i) => i + 1) as x}
			{@const bottomRects = getRandomRects(height / 2 / size)}
			{@const topRects = getRandomRects(height / 2 / size)}
			{#each bottomRects as y}
				<rect
					x={(x - 1) * size}
					y={height - size * y}
					width={size}
					height={size}
					style="fill: {bgColor}; stroke: {bgColor}; opacity: {Math.random().toFixed(2)};"
				/>
			{/each}
			{#each topRects as y}
				<rect
					x={(x - 1) * size}
					y={size * (y - 1)}
					width={size}
					height={size}
					style="fill: {bgColor}; stroke: {bgColor}; opacity: {Math.random().toFixed(2)};"
				/>
			{/each}
		{/each}
	</svg>
	<div class="relative z-10">
		{@render children()}
	</div>
</div>
