// apps/web/src/lib/components/ProjectCard.svelte
<script lang="ts">
	import BackgroundGrid from './BackgroundGrid.svelte';

	interface Project {
		slug: string;
		title: string;
		description: string;
		tech: string[];
		github?: string;
		web?: string;
	}

	interface Props {
		project: Project;
	}

	let { project }: Props = $props();
</script>

<div class="corner-brackets group relative bg-[#131313] p-5">
		<BackgroundGrid />

	<article class="relative z-10">
		<a href="/projects/{project.slug}" class="block" title="{project.title} - {project.description}">
			<h3 class="text-lg md:text-xl font-medium text-white hover:text-gray-300 transition-colors">
				{project.title}
			</h3>
		</a>
		<p class="mt-2 block text-base md:text-lg text-gray-200">
			{project.description}
		</p>
		<div class="mt-3 flex flex-wrap gap-2">
			{#each project.tech as tech}
				<span class="bg-neutral-600 px-2 py-1 text-sm text-white">
					{tech}
				</span>
			{/each}
		</div>
		<div class="mt-3 flex items-center gap-2 md:gap-5">
			<a
				href="/projects/{project.slug}"
				title="{project.title} project overview"
				class="text-blue-400 hover:text-blue-300 transition-colors text-sm md:text-base"
			>
				Overview
			</a>
			{#if project.github}
			-
				<a
					href={project.github}
					target="_blank"
					rel="noopener noreferrer"
					title="View {project.title} source code on GitHub"
					class="text-blue-400 hover:text-blue-300 transition-colors text-sm md:text-base"
				>
					GitHub
				</a>
			{/if}
			{#if project.web}
			-
				<a
					href={project.web}
					target="_blank"
					rel="noopener noreferrer"
					title="View {project.title} live demo"
					class="text-blue-400 hover:text-blue-300 transition-colors text-sm md:text-base"
				>
					Live Demo
				</a>
			{/if}
		</div>
	</article>
</div>

// components/ProjectCard.vue
<script setup lang="ts">
defineProps<{
    project: {
        title: string;
        description: string;
        tech: string[];
        github?: string;
        web?: string;
    };
}>();
</script>

<template>
    <div class="corner-brackets-simple bg-neutral-800 group relative p-[20px]">
        <ClientOnly lazy>
            <BackgroundGrid />
        </ClientOnly>

        <article class="relative z-10">
            <h3 class="text-xl block w-full font-medium text-white">
                {{ project.title }}
            </h3>
            <p class="text-gray-200 block mt-2 text-lg">
                {{ project.description }}
            </p>
            <div class="mt-3 flex flex-wrap gap-2">
                <span
                    v-for="tech in project.tech"
                    :key="tech"
                    class="px-2 py-1 bg-neutral-600 text-white text-sm"
                >
                    {{ tech }}
                </span>
            </div>
            <div class="space-x-5">
                <NuxtLink
                    v-if="project.github"
                    :to="project.github"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="inline-block mt-3 text-blue-400 hover:text-blue-300"
                >
                    View on GitHub →
                </NuxtLink>
                <NuxtLink
                    v-if="project.web"
                    :to="project.web"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="inline-block mt-3 text-blue-400 hover:text-blue-300"
                >
                    View Live →
                </NuxtLink>
            </div>
        </article>
    </div>
</template>
